# Generated by Django 3.1.7 on 2021-04-14 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_prod', to=settings.AUTH_USER_MODEL, verbose_name='Wish author'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_prod', to='product.product', verbose_name='Wish product item'),
        ),
    ]
